### ISSUE TITLE
gclient sync -D hangs forever

### ISSUE THREAD

**Issue by dr-ni** [libcamera-org/chromium#1]
I'm trying to build chromium as described here:
https://github.com/linux-surface/linux-surface/wiki/Camera-Support

```
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH="$PATH:${HOME}/depot_tools"

$ mkdir ~/chromium && cd ~/chromium
$ fetch --nohooks chromium
$ cd src

$ sudo apt upgrade -y
$ sudo apt install gnome-keyring libva-dev libdri2-dev mesa-common-dev python python2.7 libx11-xcb-dev
$ sudo ./build/install-build-deps.sh --unsupported
$ gclient runhooks


$ git remote add github https://github.com/libcamera-org/chromium.git
$ git fetch github
$ git checkout -b surface github/surface

$ gclient sync -D
```

then all is hanging forever on:

```
Running hooks:  15% (16/101) clang        
________ running 'vpython src/tools/clang/scripts/update.py' in '/media/uwe/sd_128gb_ext4/chromium'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz .......... Done.
Running hooks:  25% (26/101) clang_format_linux
```

any advice?

**Comment by rkorn86** [comment]
I have exactly the same issue on Archlinux.
```
Hook 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' took 36.14 secs
Running hooks:   8% ( 9/101) sysroot_x86  
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/opt/projects/chromium-libcamera/chromium'
Installing Debian sid i386 root image: /opt/projects/chromium-libcamera/chromium/src/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d967bcef40477dbc39acef141ff22bf73f3e7cdb/debian_sid_i386_sysroot.tar.xz
Running hooks:  11% (12/101) sysroot_x64   
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/opt/projects/chromium-libcamera/chromium'
Installing Debian sid amd64 root image: /opt/projects/chromium-libcamera/chromium/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/5f64b417e1018dcf8fcc81dc2714e0f264b9b911/debian_sid_amd64_sysroot.tar.xz
Running hooks:  15% (16/101) clang        
________ running 'vpython src/tools/clang/scripts/update.py' in '/opt/projects/chromium-libcamera/chromium'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz .......... Done.
Running hooks:  25% (26/101) clang_format_linux
```

And then hangs....

No problems on master branch from https://github.com/chromium/chromium

**Comment by rkorn86** [comment]
After killing the hanging process the following log is shown:
```
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/opt/projects/chromium-libcamera/chromium'
0> Failed to fetch file gs://chromium-clang-format/1baf0089e895c989a311b6a38ed94d0e8be4c0a7 for src/buildtools/linux64/clang-format, skipping. [Err: /opt/projects/chromium-libcamera/chromium/src/third_party/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Failed to fetch file gs://chromium-clang-format/1baf0089e895c989a311b6a38ed94d0e8be4c0a7 for src/buildtools/linux64/clang-format. [Err: /opt/projects/chromium-libcamera/chromium/src/third_party/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Downloading 1 files took 393.142655 second(s)
Error: Command 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /opt/projects/chromium-libcamera/chromium
0> Failed to fetch file gs://chromium-clang-format/1baf0089e895c989a311b6a38ed94d0e8be4c0a7 for src/buildtools/linux64/clang-format, skipping. [Err: /opt/projects/chromium-libcamera/chromium/src/third_party/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Failed to fetch file gs://chromium-clang-format/1baf0089e895c989a311b6a38ed94d0e8be4c0a7 for src/buildtools/linux64/clang-format. [Err: /opt/projects/chromium-libcamera/chromium/src/third_party/depot_tools/external_bin/gsutil/gsutil_4.28/gsutil/third_party/boto/boto/pyami/config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
]
Downloading 1 files took 393.142655 second(s)

Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' took 394.16 secs
```

**Comment by rkorn86** [comment]
Seems to have something to do with multithreading and having multiple CPUs.
This one process hanging, consumes 100% CPU on one core.
When running `gclient sync -D` multiple times in parallel, one of the processes finishes this step, but hangs on some later.
I had to re-run this step on my 16 Core vSphere several times with 4 threads in parallel each time.

**Comment by dr-ni** [comment]
if I use more verbose output
```
gclient sync -D -vv
```
is showing this as last output:

```
...
...
...
----------------------------------------
[0:00:34] Started.
_____ src/third_party/angle/third_party/VK-GL-CTS/src at 9e07e4424cd4b64ec55d0050185f93e94f38ed0d
[0:00:35] Finished running: git config remote.origin.url
[0:00:35] Finished running: git rev-list -n 1 HEAD
[0:00:35] Finished running: git rev-parse --abbrev-ref=strict HEAD
[0:00:44] Finished running: git rev-list -n 1 HEAD
[0:00:44] Up-to-date; skipping checkout.
[0:00:44] Finished running: git rev-parse HEAD
Checked out revision 9e07e4424cd4b64ec55d0050185f93e94f38ed0d
[0:00:44] Finished running: git rev-parse --verify HEAD
[0:00:44] Finished.
----------------------------------------
________ running 'vpython src/build/landmines.py' in '/media/uwe/sd_128gb_ext4/chromium'
Hook 'vpython src/build/landmines.py' took 37.64 secs
________ running 'vpython src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/tools/remove_stale_pyc_files.py src/android_webview/tools src/build/android src/gpu/gles2_conform_support src/infra src/ppapi src/printing src/third_party/blink/renderer/build/scripts src/third_party/blink/tools src/third_party/catapult src/tools' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/buildtools/ensure_gn_version.py git_revision:53d92014bf94c3893886470a1c7c1289f8818db0' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/tools/clang/scripts/update.py' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/media/uwe/sd_128gb_ext4/chromium'
________ running 'vpython src/build/util/lastchange.py -m SKIA_COMMIT_HASH -s src/third_party/skia --header src/skia/ext/skia_commit_hash.h' in '/media/uwe/sd_128gb_ext4/chromium
```

**Comment by dr-ni** [comment]
I do not exactly know why - but after a complete new trial from scratch and one restart of gclient sync -D after some errors - it suddenly was working?!

```
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ git remote add github https://github.com/libcamera-org/chromium.git
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ git fetch github
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (40/40), done.
remote: Total 57 (delta 40), reused 40 (delta 40), pack-reused 17
Entpacke Objekte: 100% (57/57), 28.49 KiB | 174.00 KiB/s, fertig.
Von https://github.com/libcamera-org/chromium
 * [neuer Branch]              surface     -> github/surface
 * [neuer Branch]              surface-R87 -> github/surface-R87
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ git checkout -b surface github/surface
Aktualisiere Dateien: 100% (142819/142819), fertig.
Vorherige Position von HEAD war 935c1c3eed6b Roll Chrome Win32 PGO Profile
Branch 'surface' folgt nun Remote-Branch 'surface' von 'github'.
Zu neuem Branch 'surface' gewechselt
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ gclient sync -D
Syncing projects: 100% (117/117), done.                                                                                       

________ deleting 'src/third_party/eigen3/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/farmhash/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/fp16/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/freetype-testing/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/gemmlowp/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/highway/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/libjxl/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/neon_2_sse/src' in '/media/uwe/sd_128gb_ext4/chromium'

WARNING: 'src/third_party/ots/src' has been moved from DEPS to a higher level checkout. The git folder containing all the local branches has been saved to /media/uwe/sd_128gb_ext4/chromium/old_src_third_party_ots_src.git.
If you don't care about its state you can safely remove that folder to free up space.

________ deleting 'src/third_party/ruy/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/tflite/src' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/vulkan-deps' in '/media/uwe/sd_128gb_ext4/chromium'

________ deleting 'src/third_party/dawn/third_party/tint' in '/media/uwe/sd_128gb_ext4/chromium'
Hook 'vpython src/build/landmines.py' took 17.37 secs
Running hooks:   5% ( 6/101) nacltools                     
________ running 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' in '/media/uwe/sd_128gb_ext4/chromium'
INFO: --Syncing pnacl_newlib to revision f45e60c61cc1ae967e6f5fefc8f3e560e3b3c501--
INFO: Downloading package archive: binutils_x86_64_linux.tgz (1/46)
INFO: Downloading package archive: binutils_x86_x86_64_linux.tgz (2/46)
INFO: Downloading package archive: compiler_rt_bc_arm_bc.tgz (3/46)
INFO: Downloading package archive: compiler_rt_bc_i686_bc.tgz (4/46)
INFO: Downloading package archive: compiler_rt_bc_le32.tgz (5/46)
INFO: Downloading package archive: compiler_rt_bc_x86_64_bc.tgz (6/46)
INFO: Downloading package archive: core_sdk_libs_arm.tgz (7/46)
INFO: Downloading package archive: core_sdk_libs_i686.tgz (8/46)
INFO: Downloading package archive: core_sdk_libs_le32.tgz (9/46)
INFO: Downloading package archive: core_sdk_libs_mipsel.tgz (10/46)
INFO: Downloading package archive: core_sdk_libs_x86_64.tgz (11/46)
INFO: Downloading package archive: libcxx_arm.tgz (12/46)
INFO: Downloading package archive: libcxx_arm_bc.tgz (13/46)
INFO: Downloading package archive: libcxx_i686.tgz (14/46)
INFO: Downloading package archive: libcxx_i686_bc.tgz (15/46)
INFO: Downloading package archive: libcxx_le32.tgz (16/46)
INFO: Downloading package archive: libcxx_mipsel.tgz (17/46)
INFO: Downloading package archive: libcxx_x86_64.tgz (18/46)
INFO: Downloading package archive: libcxx_x86_64_bc.tgz (19/46)
INFO: Downloading package archive: libgcc_eh_arm.tgz (20/46)
INFO: Downloading package archive: libgcc_eh_mips32.tgz (21/46)
INFO: Downloading package archive: libs_support_arm.tgz (22/46)
INFO: Downloading package archive: libs_support_arm_bc.tgz (23/46)
INFO: Downloading package archive: libs_support_i686.tgz (24/46)
INFO: Downloading package archive: libs_support_i686_bc.tgz (25/46)
INFO: Downloading package archive: libs_support_le32.tgz (26/46)
INFO: Downloading package archive: libs_support_mipsel.tgz (27/46)
INFO: Downloading package archive: libs_support_translator_arm.tgz (28/46)
INFO: Downloading package archive: libs_support_translator_arm_nonsfi.tgz (29/46)
INFO: Downloading package archive: libs_support_translator_mips32.tgz (30/46)
INFO: Downloading package archive: libs_support_translator_x86_32.tgz (31/46)
INFO: Downloading package archive: libs_support_translator_x86_32_nonsfi.tgz (32/46)
INFO: Downloading package archive: libs_support_translator_x86_64.tgz (33/46)
INFO: Downloading package archive: libs_support_x86_64.tgz (34/46)
INFO: Downloading package archive: libs_support_x86_64_bc.tgz (35/46)
INFO: Downloading package archive: llvm_x86_64_linux.tgz (36/46)
INFO: Downloading package archive: metadata.tgz (37/46)
INFO: Downloading package archive: newlib_arm.tgz (38/46)
INFO: Downloading package archive: newlib_arm_bc.tgz (39/46)
INFO: Downloading package archive: newlib_i686.tgz (40/46)
INFO: Downloading package archive: newlib_i686_bc.tgz (41/46)
INFO: Downloading package archive: newlib_le32.tgz (42/46)
INFO: Downloading package archive: newlib_mipsel.tgz (43/46)
INFO: Downloading package archive: newlib_x86_64.tgz (44/46)
INFO: Downloading package archive: newlib_x86_64_bc.tgz (45/46)
INFO: Downloading package archive: unsandboxed_runtime_x86_64_linux.tgz (46/46)
INFO: --Syncing pnacl_translator to revision f45e60c61cc1ae967e6f5fefc8f3e560e3b3c501--
INFO: Downloading package archive: sandboxed_translators.tgz (1/1)
INFO: Extracting package (pnacl_newlib) to directory: /media/uwe/sd_128gb_ext4/chromium/src/native_client/toolchain/linux_x86/pnacl_newlib
INFO: Extracting binutils_x86_64_linux.tgz (1/51)
|------------------------------------------------|
..................................................
INFO: Extracting binutils_x86_x86_64_linux.tgz (2/51)
|------------------------------------------------|
..................................................
INFO: Extracting compiler_rt_bc_arm_bc.tgz (3/51)
|------------------------------------------------|
.....
INFO: Extracting compiler_rt_bc_i686_bc.tgz (4/51)
|------------------------------------------------|
.....
INFO: Extracting compiler_rt_bc_le32.tgz (5/51)
|------------------------------------------------|
.....
INFO: Extracting compiler_rt_bc_x86_64_bc.tgz (6/51)
|------------------------------------------------|
.....
INFO: Extracting core_sdk_libs_arm.tgz (7/51)
|------------------------------------------------|
..................................................
INFO: Extracting core_sdk_libs_i686.tgz (8/51)
|------------------------------------------------|
..................................................
INFO: Extracting core_sdk_libs_le32.tgz (9/51)
|------------------------------------------------|
..................................................
INFO: Extracting core_sdk_libs_mipsel.tgz (10/51)
|------------------------------------------------|
..................................................
INFO: Extracting core_sdk_libs_x86_64.tgz (11/51)
|------------------------------------------------|
..................................................
INFO: Extracting driver_x86_64_linux.tgz (12/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_arm.tgz (13/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_arm_bc.tgz (14/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_i686.tgz (15/51)
|------------------------------------------------|

INFO: Extracting libcxx_i686_bc.tgz (16/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_le32.tgz (17/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_mipsel.tgz (18/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_x86_64.tgz (19/51)
|------------------------------------------------|
.................................................
INFO: Extracting libcxx_x86_64_bc.tgz (20/51)
|------------------------------------------------|
.................................................
INFO: Extracting libgcc_eh_arm.tgz (21/51)
|------------------------------------------------|

INFO: Extracting libgcc_eh_mips32.tgz (22/51)
|------------------------------------------------|

INFO: Extracting libgcc_eh_x86_32.tgz (23/51)
|------------------------------------------------|
.
INFO: Extracting libgcc_eh_x86_64.tgz (24/51)
|------------------------------------------------|
.
INFO: Extracting libs_support_arm.tgz (25/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_arm_bc.tgz (26/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_i686.tgz (27/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_i686_bc.tgz (28/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_le32.tgz (29/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_mipsel.tgz (30/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_arm.tgz (31/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_arm_nonsfi.tgz (32/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_mips32.tgz (33/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_x86_32.tgz (34/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_x86_32_nonsfi.tgz (35/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_translator_x86_64.tgz (36/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_x86_64.tgz (37/51)
|------------------------------------------------|
..................................................
INFO: Extracting libs_support_x86_64_bc.tgz (38/51)
|------------------------------------------------|
..................................................
INFO: Extracting llvm_x86_64_linux.tgz (39/51)
|------------------------------------------------|
..................................................
INFO: Extracting metadata.tgz (40/51)
|------------------------------------------------|
......................................
INFO: Extracting newlib_arm.tgz (41/51)
|------------------------------------------------|
.................................................
INFO: Extracting newlib_arm_bc.tgz (42/51)
|------------------------------------------------|
..................................................
INFO: Extracting newlib_i686.tgz (43/51)
|------------------------------------------------|
..................................................
INFO: Extracting newlib_i686_bc.tgz (44/51)
|------------------------------------------------|
..................................................
INFO: Extracting newlib_le32.tgz (45/51)
|------------------------------------------------|
.................................................
INFO: Extracting newlib_mipsel.tgz (46/51)
|------------------------------------------------|
.................................................
INFO: Extracting newlib_x86_64.tgz (47/51)
|------------------------------------------------|
.................................................
INFO: Extracting newlib_x86_64_bc.tgz (48/51)
|------------------------------------------------|
..................................................
INFO: Extracting unsandboxed_runtime_arm_linux.tgz (49/51)
|------------------------------------------------|
..................................................
INFO: Extracting unsandboxed_runtime_x86_32_linux.tgz (50/51)
|------------------------------------------------|
..............................................
INFO: Extracting unsandboxed_runtime_x86_64_linux.tgz (51/51)
|------------------------------------------------|
.........................
INFO: Extracting package (pnacl_translator) to directory: /media/uwe/sd_128gb_ext4/chromium/src/native_client/toolchain/linux_x86/pnacl_translator
INFO: Extracting sandboxed_translators.tgz (1/1)
|------------------------------------------------|
.................................................
Hook 'vpython src/build/download_nacl_toolchains.py --mode nacl_core_sdk sync --extract' took 48.37 secs
Running hooks:   8% ( 9/101) sysroot_x86  
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/media/uwe/sd_128gb_ext4/chromium'
Installing Debian sid i386 root image: /media/uwe/sd_128gb_ext4/chromium/src/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d967bcef40477dbc39acef141ff22bf73f3e7cdb/debian_sid_i386_sysroot.tar.xz
Hook 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 13.42 secs
Running hooks:  11% (12/101) sysroot_x64   
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/media/uwe/sd_128gb_ext4/chromium'
Installing Debian sid amd64 root image: /media/uwe/sd_128gb_ext4/chromium/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/5f64b417e1018dcf8fcc81dc2714e0f264b9b911/debian_sid_amd64_sysroot.tar.xz
Hook 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 13.78 secs
Running hooks:  15% (16/101) clang        
________ running 'vpython src/tools/clang/scripts/update.py' in '/media/uwe/sd_128gb_ext4/chromium'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz .......... Done.
Running hooks:  25% (26/101) clang_format_linux
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/buildtools/linux64/clang-format@1baf0089e895c989a311b6a38ed94d0e8be4c0a7...
Downloading 1 files took 19.464971 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' took 20.46 secs
Running hooks:  34% (35/101) msan_chained_origins
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz@f1e29227f344393fbe410520d9b1b2331017fb52...
Downloading 1 files took 27.308341 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' took 31.37 secs
Running hooks:  35% (36/101) msan_no_origins     
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz@c67514475887c122e02905a4f184128e3488c07d...
Downloading 1 files took 25.276898 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' took 30.62 secs
Running hooks:  36% (37/101) wasm_fuzzer    
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s src/v8/test/fuzzer/wasm_corpus.tar.gz.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/v8/test/fuzzer/wasm_corpus.tar.gz@f6b95b7dd8300efa84b6382f16cfcae4ec9fa108...
0> Removed src/v8/test/fuzzer/wasm_corpus...
0> Extracting 15291 entries from src/v8/test/fuzzer/wasm_corpus.tar.gz to src/v8/test/fuzzer/wasm_corpus
Downloading 1 files took 10.248150 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth -u --bucket v8-wasm-fuzzer -s src/v8/test/fuzzer/wasm_corpus.tar.gz.sha1' took 10.92 secs
Running hooks:  37% (38/101) node_linux64
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/12.14.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/third_party/node/linux/node-linux-x64.tar.gz@4572d3801500bcbebafadf203056d6263c840cda...
0> Removed src/third_party/node/linux/node-linux-x64...
0> Extracting 5551 entries from src/third_party/node/linux/node-linux-x64.tar.gz to src/third_party/node/linux/node-linux-x64
Downloading 1 files took 12.294049 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/12.14.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' took 13.40 secs
Running hooks:  40% (41/101) webui_node_modules
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs -s src/third_party/node/node_modules.tar.gz.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/third_party/node/node_modules.tar.gz@f44430862b93f5fa7edc6a27e175c4defa0140bc...
0> Removed src/third_party/node/node_modules...
0> Extracting 9837 entries from src/third_party/node/node_modules.tar.gz to src/third_party/node/node_modules
Downloading 1 files took 10.222196 second(s)
Hook 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs -s src/third_party/node/node_modules.tar.gz.sha1' took 10.99 secs
Running hooks:  51% (52/101) Fetch Android AFDO profile            
________ running 'vpython src/tools/download_optimization_profile.py --newest_state=src/chrome/android/profiles/newest.txt --local_state=src/chrome/android/profiles/local.txt --output_name=src/chrome/android/profiles/afdo.prof --gs_url_base=chromeos-prebuilt/afdo-job/llvm' in '/media/uwe/sd_128gb_ext4/chromium'
Traceback (most recent call last):
  File "src/tools/download_optimization_profile.py", line 150, in <module>
    sys.exit(main())
  File "src/tools/download_optimization_profile.py", line 144, in main
    RetrieveProfile(up_to_date_profile, new_tmpfile, args.gs_url_base)
  File "src/tools/download_optimization_profile.py", line 83, in RetrieveProfile
    with contextlib.closing(urllib2.urlopen(gs_url)) as u:
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
Error: Command 'vpython src/tools/download_optimization_profile.py --newest_state=src/chrome/android/profiles/newest.txt --local_state=src/chrome/android/profiles/local.txt --output_name=src/chrome/android/profiles/afdo.prof --gs_url_base=chromeos-prebuilt/afdo-job/llvm' returned non-zero exit status 1 in /media/uwe/sd_128gb_ext4/chromium
Traceback (most recent call last):
  File "src/tools/download_optimization_profile.py", line 150, in <module>
    sys.exit(main())
  File "src/tools/download_optimization_profile.py", line 144, in main
    RetrieveProfile(up_to_date_profile, new_tmpfile, args.gs_url_base)
  File "src/tools/download_optimization_profile.py", line 83, in RetrieveProfile
    with contextlib.closing(urllib2.urlopen(gs_url)) as u:
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/media/uwe/sd_128gb_ext4/depot_tools/bootstrap-2@3.8.10.chromium.17_bin/python/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

Hook 'vpython src/tools/download_optimization_profile.py --newest_state=src/chrome/android/profiles/newest.txt --local_state=src/chrome/android/profiles/local.txt --output_name=src/chrome/android/profiles/afdo.prof --gs_url_base=chromeos-prebuilt/afdo-job/llvm' took 16.14 secs
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ gclient sync -D
Syncing projects: 100% (117/117), done.                                                                                       
Running hooks:  60% (61/101) subresource-filter-ruleset            
________ running 'vpython src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-ads-detection -s src/third_party/subresource-filter-ruleset/data/UnindexedRules.sha1' in '/media/uwe/sd_128gb_ext4/chromium'
0> Downloading src/third_party/subresource-filter-ruleset/data/UnindexedRules@83bced6c2676ed8d7c57a84c9a8d4f76c08f79e2...
Downloading 1 files took 7.434846 second(s)
Running hooks: 100% (101/101), done.                                              
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ gn gen out/Default --args="is_debug=false is_component_build=true symbol_level=0 enable_nacl=false blink_symbol_level=0 use_gold=false use_sysroot=false is_clang=true clang_use_chrome_plugins=false use_lld=false is_clang=true use_custom_libcxx=true libcxx_abi_unstable=false use_gnome_keyring=false use_libcamera=true"
Done. Made 15628 targets from 2619 files in 6113ms
uwe@Go2:/media/uwe/sd_128gb_ext4/chromium/src$ autoninja -C out/Default chrome
```
